name       : abcm2ps
version    : 8.13.9
release    : 3
source     :
    - http://moinejf.free.fr/abcm2ps-8.13.9.tar.gz : 372bc6d5bb5ba087b71abeb6240c806f940a59e9664f46e5f4f1faec52e815a7
license    : GPL-2.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
