name        : abcm2ps
version     : 8.13.7
release     : 1
source      :
    - http://moinejf.free.fr/abcm2ps-8.13.7.tar.gz : 00b7704c512c0db4a747050ec93d4b13e16c50798cff375e2c809a6144dcafc5
license     : GPL-2.0
component   : multimedia.audio
summary     : abcm2ps is a command line program which converts ABC to music sheet
description : |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps:
    - pkgconfig(pangomm-1.4)
setup : |
    %configure --docdir=/usr/share/doc
build : |
    %make
install : |
    %make_install
