name       : abcm2ps
version    : 8.13.24
release    : 13
source     :
    - https://github.com/leesavide/abcm2ps/archive/v8.13.24.tar.gz : 12116ca374e4a71575bfd82a7a44e27e4bbdc7a0cbcc423b29ca3d5e149ab29b
license    : GPL-3.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
