name       : abcm2ps
version    : 8.13.11
release    : 5
source     :
    - http://moinejf.free.fr/abcm2ps-8.13.11.tar.gz : 17afce68bb3709ccab9d89d81bdb9b7896224426094ce35913856bce09da62d4
license    : GPL-2.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
