name       : abcm2ps
version    : 8.14.4
release    : 15
source     :
    - https://github.com/leesavide/abcm2ps/archive/v8.14.4.tar.gz : ce2708550725c2ec54022b4c4a076dad7ea7f33d9cd588e7df58bb5c989eccb4
license    : GPL-3.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
