name       : abcm2ps
version    : 8.14.14
release    : 16
source     :
    - https://github.com/leesavide/abcm2ps/archive/v8.14.14.tar.gz : 5b39ca08cd5e0d1992071b0be9eb77304489823824570236c4df4dc0f8b33aab
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
