name       : abcm2ps
version    : 8.13.18
release    : 11
source     :
    - https://github.com/leesavide/abcm2ps/archive/v8.13.18.tar.gz : 4855a55ab2ee046e2d11ee30f453a5bef81870d32421fde4305c4850a3c68760
license    : GPL-3.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
