name       : abcm2ps
version    : 8.13.19
release    : 12
source     :
    - https://github.com/leesavide/abcm2ps/archive/v8.13.19.tar.gz : 587edc57cb4155516fff6d5834ebc3192a6b27539c50ef25ae1ae0240c5676f3
license    : GPL-3.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
