name       : abcm2ps
version    : 8.13.8
release    : 2
source     :
    - http://moinejf.free.fr/abcm2ps-8.13.8.tar.gz : 8ecbf6ae95093f784237020980fca2cd7345b347a3449a3aca9e4064db2d74e6
license    : GPL-2.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
