name       : abcm2ps
version    : 8.13.17
release    : 10
source     :
    - https://github.com/leesavide/abcm2ps/archive/v8.13.17.tar.gz : 639755b7760ddb3f293ab686b23ff7d5937df13f1c388d08e34ceaee319249e9
license    : GPL-3.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    chmod +x ./configure
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
