name       : abcm2ps
version    : 8.13.10
release    : 4
source     :
    - http://moinejf.free.fr/abcm2ps-8.13.10.tar.gz : 96a8133b587b8b8b92d485f52848134eb587379ff308b708a8e0bb64224bd90a
license    : GPL-2.0
component  : multimedia.audio
summary    : abcm2ps is a command line program which converts ABC to music sheet
description: |
    abcm2ps is a command line program which converts ABC to music sheet in PostScript or SVG format. It is an extension of abc2ps which may handle many voices per staff
builddeps  :
    - pkgconfig(pangomm-1.4)
setup      : |
    %configure --docdir=/usr/share/doc
build      : |
    %make
install    : |
    %make_install
